### ISSUE TITLE
fizzbuzz 구현

### ISSUE THREAD

**Issue by kim8mumu** [kim8mumu/fizzbuzz-for-me#1]
## 목표

나 혼자 완성해 보는 fizz buzz

## 요구사항

- 범위 : 1 ~ 20까지의 정수

## Tasks

- [ ] Print 'fizz' if i is times of 3.
- [ ] Print 'buzz' if i is times of 5.
- [ ] Print 'fizzbuzz' if i is times of 15.
- [ ] Print i itself for any other cases.

## References

https://en.wikipedia.org/wiki/Fizz_buzz
